/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppLibraryRouteImport } from './routes/app.library'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AppChatStoryIdRouteImport } from './routes/app.chat.$storyId'
import { Route as AppCharactersNewRouteImport } from './routes/app.characters.new'
import { Route as AppCharactersCharacterIdEditRouteImport } from './routes/app.characters.$characterId.edit'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatStoryIdRoute = AppChatStoryIdRouteImport.update({
  id: '/chat/$storyId',
  path: '/chat/$storyId',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersNewRoute = AppCharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCharactersCharacterIdEditRoute =
  AppCharactersCharacterIdEditRouteImport.update({
    id: '/characters/$characterId/edit',
    path: '/characters/$characterId/edit',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/characters/new': typeof AppCharactersNewRoute
  '/app/chat/$storyId': typeof AppChatStoryIdRoute
  '/app/characters/$characterId/edit': typeof AppCharactersCharacterIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/characters/new': typeof AppCharactersNewRoute
  '/app/chat/$storyId': typeof AppChatStoryIdRoute
  '/app/characters/$characterId/edit': typeof AppCharactersCharacterIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/api/chat': typeof ApiChatRoute
  '/app/library': typeof AppLibraryRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/characters/new': typeof AppCharactersNewRoute
  '/app/chat/$storyId': typeof AppChatStoryIdRoute
  '/app/characters/$characterId/edit': typeof AppCharactersCharacterIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/api/chat'
    | '/app/library'
    | '/app/settings'
    | '/app/'
    | '/app/characters/new'
    | '/app/chat/$storyId'
    | '/app/characters/$characterId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/api/chat'
    | '/app/library'
    | '/app/settings'
    | '/app'
    | '/app/characters/new'
    | '/app/chat/$storyId'
    | '/app/characters/$characterId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/reset-password'
    | '/api/chat'
    | '/app/library'
    | '/app/settings'
    | '/app/'
    | '/app/characters/new'
    | '/app/chat/$storyId'
    | '/app/characters/$characterId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/library': {
      id: '/app/library'
      path: '/library'
      fullPath: '/app/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/chat/$storyId': {
      id: '/app/chat/$storyId'
      path: '/chat/$storyId'
      fullPath: '/app/chat/$storyId'
      preLoaderRoute: typeof AppChatStoryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/characters/new': {
      id: '/app/characters/new'
      path: '/characters/new'
      fullPath: '/app/characters/new'
      preLoaderRoute: typeof AppCharactersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/characters/$characterId/edit': {
      id: '/app/characters/$characterId/edit'
      path: '/characters/$characterId/edit'
      fullPath: '/app/characters/$characterId/edit'
      preLoaderRoute: typeof AppCharactersCharacterIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppLibraryRoute: typeof AppLibraryRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCharactersNewRoute: typeof AppCharactersNewRoute
  AppChatStoryIdRoute: typeof AppChatStoryIdRoute
  AppCharactersCharacterIdEditRoute: typeof AppCharactersCharacterIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppLibraryRoute: AppLibraryRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCharactersNewRoute: AppCharactersNewRoute,
  AppChatStoryIdRoute: AppChatStoryIdRoute,
  AppCharactersCharacterIdEditRoute: AppCharactersCharacterIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
