// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// CHAVE usada para persistir a preferência "Manter-me conectado"
export const KEEP_SIGNED_IN_KEY = 'lucid_keep_signed_in';

/**
 * Armazenamento híbrido: usa localStorage quando o usuário escolheu
 * "Manter-me conectado", e sessionStorage caso contrário.
 * Isso garante que a sessão expire naturalmente ao fechar o navegador
 * para usuários que não optaram pela persistência.
 */
const customStorage =
  typeof window !== 'undefined'
    ? {
        getItem: (key: string): string | null => {
          try {
            const keepSignedIn = localStorage.getItem(KEEP_SIGNED_IN_KEY) === 'true';
            return keepSignedIn
              ? localStorage.getItem(key)
              : sessionStorage.getItem(key);
          } catch {
            return null;
          }
        },
        setItem: (key: string, value: string): void => {
          try {
            const keepSignedIn = localStorage.getItem(KEEP_SIGNED_IN_KEY) === 'true';
            if (keepSignedIn) {
              localStorage.setItem(key, value);
            } else {
              sessionStorage.setItem(key, value);
            }
          } catch {
            // Silencioso em ambientes sem storage
          }
        },
        removeItem: (key: string): void => {
          try {
            localStorage.removeItem(key);
            sessionStorage.removeItem(key);
          } catch {
            // Silencioso
          }
        },
      }
    : undefined;

// Credenciais públicas do Supabase (seguro expor no cliente)
const SUPABASE_URL_DEFAULT = 'https://rjeszosetfxytazotoed.supabase.co';
const SUPABASE_KEY_DEFAULT = 'sb_publishable_-NXMuKSJF4EOfWqvM5hwIg_5OFL689T';

function createSupabaseClient() {
  // Prioridade: variável de build do Vite > process.env (SSR) > fallback hardcoded
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== 'undefined' ? process.env?.SUPABASE_URL : undefined) ||
    SUPABASE_URL_DEFAULT;

  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== 'undefined' ? process.env?.SUPABASE_PUBLISHABLE_KEY : undefined) ||
    SUPABASE_KEY_DEFAULT;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: customStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

